## Define de build of the main engine

Import('*') # everything
libs = [ 'tinyobj'
        ,'GL'
        ,'glfw'
        ,'glew'
        ,'glm'
        ,'boost']
env.Append(LIBS = libs)

soul = env.Program('soul', ['exp.cpp'])
Depends(soul, tinyobj)
Install('#./bin', 'soul')
Default('soul') # define a default target

# use a pound (#) in path name to force interpretation from the sconstruct top level call
# paths are normally relative to the sconscript (except for above statement)
