## Define de build of the main engine

Import('*') # everything
libs = [ 'tinyobj'
        ,'GL'
        ,'glfw'
        ,'GLEW'
        ,'lua'
        ]
soul.Append(LIBS = libs)

print(str(soul_s))

soul_b = soul.Program('soul', soul_s)
Depends(soul_b, tiny_h)
Depends(soul_b, tinyobj)
Install('#./bin', 'soul')
Default('#./bin') # define a default target

# use a pound (#) in path name to force interpretation from the sconstruct top level call
# paths are normally relative to the sconscript (except for above statement)
